version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false # Set to true for stricter builds later

python:
  install:
    - requirements: requirements_docs.txt